services:
  server:
    environment:
      NODE_ENV: production
      PORT: ${PORT_SERVER}
    ports: []
    restart: unless-stopped
    build:
      context: ./server
      args:
        MODE: production
    command: "node server.js"
    working_dir: /app
    networks:
      - traefik

  client:
    environment:
      NODE_ENV: production
      PORT: ${PORT_CLIENT}
    ports: []
    restart: unless-stopped
    build:
      context: ./client
      args:
        MODE: production
    networks:
      - traefik

networks:
  traefik:
    external: true
