services:
  server:
    environment:
      NODE_ENV: production
    ports: []
    restart: unless-stopped
    build:
      context: ./server
      args:
        MODE: production
    command: "node server.js"
    working_dir: /app
    networks:
      - traefik

  client:
    environment:
      NODE_ENV: production
    ports: []
    restart: unless-stopped
    build:
      context: ./client
      args:
        MODE: production
    command: |
      sh -c "bunx serve dist --port 3000 --single"
    working_dir: /app
    networks:
      - traefik

networks:
  traefik:
    external: true
